#include <syscalls.h>

SYSCALL_VOID_1(_exit, __NR_exit, int)

SYSCALL_3(_read, __NR_read, int, void *, size_t)
SYSCALL_3(_write, __NR_write, int, const void *, size_t)
SYSCALL_3(_open, __NR_open, const char *, int, int)
SYSCALL_1(_close, __NR_close, int)
SYSCALL_1(_unlink, __NR_unlink, const char *)
SYSCALL_3(_lseek, __NR_lseek, int, off_t, int)
SYSCALL_3(_execve, __NR_execve, char *, char **, char **)
SYSCALL_0(_fork, __NR_fork)
SYSCALL_2(_link, __NR_link, char *, char *)

SYSCALL_2(_rename, __NR_rename, const char *, const char *)
SYSCALL_2(_mkdir, __NR_mkdir, const char *, int)
SYSCALL_3(_ioctl, __NR_ioctl, int, unsigned long, void *)
SYSCALL_3(_fcntl, __NR_fcntl, int, int, void *)
SYSCALL_2(_gettimeofday, __NR_gettimeofday, struct timeval *, struct timeval *)
SYSCALL_2(_stat, __NR_stat, const char *, struct stat *)
SYSCALL_2(_fstat, __NR_fstat, int, struct stat *)
SYSCALL_1(_fsync, __NR_fsync, int)

SYSCALL_2(_kill, __NR_kill, int, int)
SYSCALL_2(_signal, __NR_signal, int, _sig_func_ptr)
SYSCALL_0(_sigreturn, __NR_sigreturn)
SYSCALL_3(_sigprocmask, __NR_sigprocmask, int, const sigset_t *, sigset_t *)
SYSCALL_3(_sigaction, __NR_sigaction, int, const struct sigaction *, struct sigaction *)

SYSCALL_0(_getpid, __NR_getpid)
SYSCALL_1(_getpidbyname, __NR_getpidbyname, const char *)
SYSCALL_2(_dlmodule_init, __NR_dlmodule_init, int *, char **)

SYSCALL_4(pthread_create, __NR_pthread_create, pthread_t *, const pthread_attr_t *, pthread_entry, void *)
SYSCALL_1(pthread_detach, __NR_pthread_detach, pthread_t)
SYSCALL_2(pthread_join, __NR_pthread_join, pthread_t, void **)
SYSCALL_0(pthread_self, __NR_pthread_self)
SYSCALL_VOID_1(pthread_exit, __NR_Pthread_exit, void *)
SYSCALL_2(pthread_kill, __NR_pthread_kill, pthread_t, int)
SYSCALL_3(pthread_sigmask, __NR_pthread_sigmask, int, const sigset_t *, sigset_t *)
SYSCALL_1(pthread_cancel, __NR_pthread_cancel, pthread_t)

SYSCALL_1(pthread_mutexattr_init, __NR_pthread_mutexattr_init, pthread_mutexattr_t *)
SYSCALL_1(pthread_mutexattr_destroy, __NR_pthread_mutexattr_destroy, pthread_mutexattr_t *)
SYSCALL_2(pthread_mutexattr_gettype, __NR_pthread_mutexattr_gettype, pthread_mutexattr_t *, int *)
SYSCALL_2(pthread_mutexattr_settype, __NR_pthread_mutexattr_settype, pthread_mutexattr_t *, int)
SYSCALL_2(pthread_mutexattr_getpshared, __NR_pthread_mutexattr_getpshared, pthread_mutexattr_t *, int *)
SYSCALL_2(pthread_mutexattr_setpshared, __NR_pthread_mutexattr_setpshared, pthread_mutexattr_t *, int)

SYSCALL_2(pthread_mutex_init, __NR_pthread_mutex_init, pthread_mutex_t *, const pthread_mutexattr_t *)
SYSCALL_1(pthread_mutex_destroy, __NR_pthread_mutex_destroy, pthread_mutex_t *)
SYSCALL_1(pthread_mutex_lock, __NR_pthread_mutex_lock, pthread_mutex_t *)
SYSCALL_1(pthread_mutex_unlock, __NR_pthread_mutex_unlock, pthread_mutex_t *)
SYSCALL_1(pthread_mutex_trylock, __NR_pthread_mutex_trylock, pthread_mutex_t *)